version: '3'
services:
  acme:
    image: robgrzel/acme:dev
    build:
      context: ./src/acme
      dockerfile: Dockerfile
      args:
        - CERT_NAME=$DOMAIN
    container_name: acme
    restart: always
    environment:
      - LETSENCRYPT_SERVER=prod
      - EMAIL=robert.grzelka@ralf-it.com
      - DOMAIN=*.$DOMAIN
      - CERT_NAME=$DOMAIN
      - KEY_FILE=gcloud.jso
    volumes:
      - .certs:/root/certs:rw
      - /root/.acme.sh/*.$DOMAIN
  proxy:
    image: robgrzel/proxy:dev
    build:
      context: ./src/proxy
      dockerfile: Dockerfile
      args:
        - HOST_TYPE=localhost
        - CERT_NAME=$DOMAIN
        - DEFAULT_HOST=$REACT_APP_HOST
    container_name: proxy
    restart: always
    environment:
      - CERT_NAME=$DOMAIN
      - DEFAULT_HOST=$REACT_APP_HOST
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - .certs/prod:/etc/nginx/certs:ro
    networks:
      - proxy
      - internal
    depends_on:
      - acme

  frontend:
    image: robgrzel/frontend:dev
    build:
      context: ./src/sys-stats
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_HOST=$REACT_APP_API_HOST
        - REACT_APP_API_PORT=443
    env_file:
      - ./src/sys-stats/.env
    container_name: frontend
    restart: always
    volumes:
      - /home/python/.local
    environment:
      - VIRTUAL_HOST=$REACT_APP_HOST
    networks:
      - internal
  api:
    image: robgrzel/api:dev
    build:
      context: ./src/api
      dockerfile: Dockerfile
    env_file:
    - ./src/api/.env
    container_name: api
    restart: always
    volumes:
      - ./src/sys-stats/public:/app/public
      - ./src/sys-stats/build:/app/build
      - /app/node_modules
    environment:
      - VIRTUAL_HOST=$REACT_APP_API_HOST
      # Fixes 502 bad gateway
      - VIRTUAL_PORT=5000
      - K8S_NODE_NAME=Docker-Compose
      - K8S_POD_NAME=?
      - K8s_POD_NAMESPACE=?

    networks:
      - internal
networks:
  proxy:
    internal: false
  internal:
    internal: true
volumes:
  vol1:

