{{- range $k, $v := .Values.apps }}
{{- if and $v.enabled $v.secrets }}
{{- $v := set $v "Chart" $.Chart }}
{{- $v := set $v "Release" $.Release }}
{{- $v := set $v "nameOverride" $k }}

---
# SECRET: {{ $k }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secrets
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with $v.extraLabels }}
      {{ toYaml . | indent 4 }}
    {{- end }}
{{- if $v.annotations }}
  annotations: {{ toYaml $v.annotations | indent 4 }}
{{- end }}
type: Opaque
data:
{{- range $v.secrets.data }}
  {{ .key }}: {{ .value | b64enc | quote }}
{{- end }}
{{- range $name := $v.secrets.files }}
{{- $path := printf "config/%s" $name }}
{{ $name | indent 2 }}: |-
{{ $.Files.Get $path  | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
