{{- range $k, $v := .Values.apps }}
{{- if and $v.enabled  $v.serviceAccount }}
{{- if $v.serviceAccount.create -}}
{{- $v := set $v "Chart" $.Chart }}
{{- $v := set $v "Release" $.Release }}
{{- $v := set $v "nameOverride" $k }}

---
# SERVICE ACCOUNT: {{ $k }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $v.serviceAccount.name | default ( include "app.fullname" . ) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    {{- with $v.extraLabels }}
      {{ toYaml . | indent 4 }}
    {{- end }}
{{- if $v.serviceAccount.annotations }}
  annotations: {{ toYaml $v.serviceAccount.annotations | indent 4 }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
