apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: {{ .Release.Namespace }}
stringData:
  .dockerconfigjson: |
    {
        "auths": {
            "https://index.docker.io/v1/": {
                "auth": "cm9iZ3J6ZWw6cm9iZXJ0MTIz"
            }
        }
    }
type: kubernetes.io/dockerconfigjson