kubed:
  # https://raw.githubusercontent.com/kubeops/kubed/release-0.12/charts/kubed/values.yaml
  # Default values for kubed.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  operator:
    # Docker registry used to pull Kubed operator image
    registry: appscode
    # Kubed operator container image
    repository: kubed
    # Security options the operator container should run with
    securityContext: {}

  # Specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  #
  # Example:
  # helm template charts/kubed \
  #   --set imagePullSecrets[0].name=sec0 \
  #   --set imagePullSecrets[1].name=sec1
  imagePullSecrets: []

  # Log level for operator
  logLevel: 3

  # Annotations applied to operator deployment
  annotations: {}

  # Annotations passed to operator pod(s).
  podAnnotations: {}

  # Security options the operator pod should run with.
  podSecurityContext:  # +doc-gen:break
    # ensure that s/a token is readable xref: https://issues.k8s.io/70679
    fsGroup: 65535

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  apiserver:
    # Port used by Kubed server
    securePort: "8443"
    # If true, uses kube-apiserver FQDN for AKS cluster to workaround https://github.com/Azure/AKS/issues/522 (default true)
    useKubeapiserverFqdnForAks: true
    healthcheck:
      # healthcheck configures the readiness and liveliness probes for the operator pod.
      enabled: false
    servingCerts:
      # If true, generates on install/upgrade the certs that allow the kube-apiserver (and potentially ServiceMonitor)
      # to authenticate operators pods. Otherwise specify certs in `apiserver.servingCerts.{caCrt, serverCrt, serverKey}`.
      generate: true
      # CA certficate used by serving certificate of Kubed server.
      caCrt: ""
      # Serving certficate used by Kubed server.
      serverCrt: ""
      # Private key for the serving certificate used by Kubed server.
      serverKey: ""

  # If true, sends usage analytics
  enableAnalytics: false

  config:
    # Set cluster-name to something meaningful to you, say, prod, prod-us-east, qa, etc.
    # so that you can distinguish notifications sent by kubed
    clusterName: "kind-localtest-ca-letsencrypt"
    # If set, configmaps and secrets from only this namespace will be synced
    configSourceNamespace: ""
    # kubeconfig file content for configmap and secret syncer
    kubeconfigContent: ""
  #  additionalOptions:
  #    - --authentication-skip-lookup