name: CI-K8S

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Save secrets
      env: 
        DOCKER_HUB_ID: ${{ secrets.DOCKER_HUB_ID }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        mkdir -p .secrets/secrets
        echo ${DOCKER_HUB_ID} > .secrets/DOCKER_HUB_ID
        echo ${DOCKER_HUB_PASSWORD} > .secrets/DOCKER_HUB_PASSWORD
    - name: Build docker-compose
      run: make dc-build-k8s
    - name: Push docker-compose
      run: |
        make dlogin
        make dc-push-k8s